2023-01-18 16:50:34,033 (27068/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-18 16:50:34,033 (27068/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-18 16:52:54,205 (29624/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-18 16:52:54,205 (29624/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-18 21:57:34,578 (82482/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-18 21:57:34,578 (82482/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-18 22:18:07,497 (95417/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-18 22:18:07,497 (95417/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-18 22:18:19,104 (95593/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-18 22:18:19,104 (95593/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-18 22:19:44,599 (82482/MainThread) pgcli.pgexecute ERROR - sql: 'FROM property SELECT property.NAME', error: SyntaxError('syntax error at or near "FROM"\nLINE 1: FROM property SELECT property.NAME\n        ^')
2023-01-18 22:19:44,603 (82482/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "FROM"\nLINE 1: FROM property SELECT property.NAME\n        ^\n'
2023-01-18 22:21:54,762 (82482/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT p.id, a.line1 FROM property p JOIN address a ON property.address_id = a.id', error: UndefinedTable('invalid reference to FROM-clause entry for table "property"\nLINE 1: ...T p.id, a.line1 FROM property p JOIN address a ON property.a...\n                                                             ^\nHINT:  Perhaps you meant to reference the table alias "p".')
2023-01-18 22:21:54,764 (82482/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: invalid reference to FROM-clause entry for table "property"\nLINE 1: ...T p.id, a.line1 FROM property p JOIN address a ON property.a...\n                                                             ^\nHINT:  Perhaps you meant to reference the table alias "p".\n'
2023-01-30 16:03:39,159 (53334/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-01-30 16:03:39,160 (53334/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-01-30 16:03:58,760 (53334/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE franklin.unit (id INT NOT NULL)', error: DuplicateObject('type "unit" already exists\nHINT:  A relation has an associated type of the same name, so you must use a name that doesn\'t conflict with any existing type.')
2023-01-30 16:03:58,763 (53334/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DuplicateObject: type "unit" already exists\nHINT:  A relation has an associated type of the same name, so you must use a name that doesn\'t conflict with any existing type.\n'
